package AgendaContacteMngUI;
import Contact.*;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.text.html.HTML;

/*@author ionut*/
public class DlgEditAddContact extends javax.swing.JDialog {

     private boolean bContactIncapsulatCreatOK;
     private Contact contactIncapsulat = null;
    
     public Contact getContactEditat() {
        return contactIncapsulat;
    }
     
     public void setContactIncapsulatCreatOK(boolean bContactIncapsulatCreatOK) {
        this.bContactIncapsulatCreatOK = bContactIncapsulatCreatOK;
    }
     
     public boolean getContactIncapsulatCreatValid(){
        return contactIncapsulat == null ? false : true;
    }
    
    /**
     * Creates new form DlgAddContact
     * @param parent
     * @param modal
     */
    public DlgEditAddContact(java.awt.Frame parent, boolean modal,boolean bIsEditare, Contact contactSel) {
        super(parent, modal);
        initComponents();
        if(bIsEditare){
            jtfNume.setEditable(false);
            jtfNume.setText(contactSel.getNume());
            jtfPrenume.setText(contactSel.getPrenume());
            jtfNumarTelefon.setText(contactSel.getNrTel());
            jtfDataNasterii.setText(contactSel.getdataNasterii());
        }else{
            jtfNume.setEditable(true);
            jtfNume.setText("");
            jtfPrenume.setText("");
            jtfNumarTelefon.setText("");
            jtfDataNasterii.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jrbFix = new javax.swing.JRadioButton();
        jrbMobil = new javax.swing.JRadioButton();
        jbAdauga = new javax.swing.JButton();
        jbAnuleaza = new javax.swing.JButton();
        jtfDataNasterii = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfNume = new javax.swing.JTextField();
        jtfPrenume = new javax.swing.JTextField();
        jtfNumarTelefon = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonGroup1.add(jrbFix);
        jrbFix.setText("Fix");

        buttonGroup1.add(jrbMobil);
        jrbMobil.setText("Mobil");

        jbAdauga.setText("Adauga");
        jbAdauga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdaugaActionPerformed(evt);
            }
        });

        jbAnuleaza.setText("Anuleaza");
        jbAnuleaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnuleazaActionPerformed(evt);
            }
        });

        jtfDataNasterii.setText("ex: ZZ.LL.AAAA");
        jtfDataNasterii.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDataNasteriiActionPerformed(evt);
            }
        });

        jLabel1.setText("Nume:");

        jLabel2.setText("Prenume:");

        jLabel3.setText("Numar Telefon:");

        jLabel4.setText("Data Nasterii:");

        jtfNume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNumeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbAdauga)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrbFix)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbMobil)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(jbAnuleaza)
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfDataNasterii)
                            .addComponent(jtfNume)
                            .addComponent(jtfPrenume)
                            .addComponent(jtfNumarTelefon, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfNume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfPrenume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfNumarTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbFix)
                    .addComponent(jrbMobil))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfDataNasterii, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAdauga)
                    .addComponent(jbAnuleaza))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAnuleazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnuleazaActionPerformed
        // TODO add your handling code here:
        contactIncapsulat = null;
        setContactIncapsulatCreatOK(false);
        
        dispose();
    }//GEN-LAST:event_jbAnuleazaActionPerformed

    private void jbAdaugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdaugaActionPerformed
      contactIncapsulat = Contact.getInstance(jtfNume.getText(), jtfPrenume.getText(), jtfNumarTelefon.getText(), jtfDataNasterii.getText());
        if(contactIncapsulat==null){
            JOptionPane.showMessageDialog(this, "contact invalid");
            setContactIncapsulatCreatOK(false);
        }else{
            setContactIncapsulatCreatOK(true);
            dispose();
        }
    }//GEN-LAST:event_jbAdaugaActionPerformed
    
    private void jtfNumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNumeActionPerformed
       
    }//GEN-LAST:event_jtfNumeActionPerformed

    private void jtfDataNasteriiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDataNasteriiActionPerformed
           // TODO add your handling code here:
    }//GEN-LAST:event_jtfDataNasteriiActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbAdauga;
    private javax.swing.JButton jbAnuleaza;
    private javax.swing.JRadioButton jrbFix;
    private javax.swing.JRadioButton jrbMobil;
    private javax.swing.JTextField jtfDataNasterii;
    private javax.swing.JTextField jtfNumarTelefon;
    private javax.swing.JTextField jtfNume;
    private javax.swing.JTextField jtfPrenume;
    // End of variables declaration//GEN-END:variables
}
